### ISSUE TITLE
Counter not working in Mozilla Firefox

### ISSUE THREAD

**Issue by kuzvac** [troublete/count-js#2]
Hi! When i setup counter, it's properly working in Chrome, IE, Edge, but in FireFox this this not working. He append numbers like 5, 10, 1 or something like that, even if i set limit to 500, or 1000. 
I think this happen in this part of code http://prntscr.com/d19qqg/direct

**Comment by troublete** [comment]
Hey so sorry for the late response, 
with the new version i published yesterday, it shouldn't be a problem anymore since i completely rewrote the module. Please try again! :)

**Comment by kuzvac** [comment]
Thank you!
